config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# resources :tasks

get "tasks", to: "tasks#index"

get "tasks/new", to: "tasks#new"
post "tasks", to: "tasks#create"

get "tasks/:id", to: "tasks#show", as: "task"

get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
patch "tasks/:id", to: "tasks#update"

delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task is defined
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTaskManager</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.label :completed %>
<%= f.check_box :completed %>
<%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="list top">
  <h1>List of tasks</h1>
</div>

<% @tasks.each do |task| %>
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
    <div class="list">
      <div class="checkbox">
       <%= check_box("tag", tag.id, {checked: task.completed}) %>
     </div>
     <div class="title">
      <p><%= link_to task.title, task_path(task) %></p>
    </div>
    <div class="delete">
      <p><%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>
    </div>
  </div>
</div>
</div>
<% end %>
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
    <div class="list">
      <%= link_to "+ Add a new task", tasks_new_path %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="list top">
  <h1>Task</h1>
</div>
<div class="list top">
  <p><%= @task.title %></p>
</div>
<div class="list">
  <p><%= @task.details %></p>
</div>
<div class="list">
  <p><%= @task.completed %></p>
</div>
<div class="list">
  <%= link_to "home", tasks_path %>
</div>
<div class="list">
  <%= link_to "edit", task_edit_path %>
</div>